from pymongo import ASCENDING, DESCENDING


def ensure_indexes(database) -> None:
    database.companies.create_index([('slug', ASCENDING)], unique=True, name='companies_slug_unique')
    database.users.create_index([('email', ASCENDING)], unique=True, name='users_email_unique')
    database.users.create_index([('company_id', ASCENDING)], name='users_company_id_idx')
    database.users.create_index([('company_id', ASCENDING), ('is_active', ASCENDING), ('role', ASCENDING)], name='users_company_status_role')
    database.users.create_index([('company_id', ASCENDING), ('group_ids', ASCENDING)], name='users_company_groups')
    database.users.create_index([('invitation_token_hash', ASCENDING)], name='users_invitation_token_hash_idx')
    database.integrations.create_index([('company_id', ASCENDING)], name='integrations_company_id_idx')
    database.integrations.create_index(
        [('company_id', ASCENDING), ('provider', ASCENDING), ('account_name_normalized', ASCENDING)],
        unique=True,
        name='integrations_company_provider_account_normalized_unique',
    )
    database.integrations.create_index([('company_id', ASCENDING), ('status', ASCENDING)], name='integrations_company_status')
    database.groups.create_index([('company_id', ASCENDING), ('name_normalized', ASCENDING)], unique=True, name='groups_company_name_unique')
    database.groups.create_index([('company_id', ASCENDING), ('status', ASCENDING)], name='groups_company_status')
    database.policies.create_index([('company_id', ASCENDING), ('name_normalized', ASCENDING)], unique=True, name='policies_company_name_unique')
    database.policies.create_index([('company_id', ASCENDING), ('category', ASCENDING)], unique=True,
        partialFilterExpression={'managed_catalog': True}, name='managed_policy_kind_unique')
    database.policies.create_index([('company_id', ASCENDING), ('status', ASCENDING)], name='policies_company_status')
    database.policies.create_index([('company_id', ASCENDING), ('scope.group_ids', ASCENDING)], name='policies_company_groups')
    database.policies.create_index([('company_id', ASCENDING), ('scope.integration_ids', ASCENDING)], name='policies_company_integrations')
    database.policy_versions.create_index([('company_id', ASCENDING), ('policy_id', ASCENDING), ('version', ASCENDING)], unique=True, name='policy_version_unique')
    database.audit_events.create_index([('company_id', ASCENDING), ('created_at', DESCENDING), ('_id', DESCENDING)], name='audit_company_recent')
    database.auth_rate_limits.create_index([('bucket_key', ASCENDING)], unique=True, name='auth_bucket_unique')
    database.auth_rate_limits.create_index([('expires_at', ASCENDING)], expireAfterSeconds=0, name='auth_bucket_expiry')
    database.prompt_runs.create_index([('company_id', ASCENDING)], name='prompt_runs_company_id_idx')
    database.prompt_runs.create_index([('user_id', ASCENDING)], name='prompt_runs_user_id_idx')
    database.prompt_runs.create_index([('created_at', ASCENDING)], name='prompt_runs_created_at_idx')
    database.prompt_runs.create_index([('company_id', ASCENDING), ('source', ASCENDING), ('created_at', DESCENDING), ('_id', DESCENDING)], name='runs_company_source_recent')
    database.prompt_runs.create_index([('company_id', ASCENDING), ('user_id', ASCENDING), ('source', ASCENDING), ('created_at', DESCENDING)], name='runs_owner_source_recent')
    database.prompt_runs.create_index([('company_id', ASCENDING), ('status', ASCENDING), ('created_at', DESCENDING)], name='runs_company_status_recent')
    database.prompt_runs.create_index([('company_id', ASCENDING), ('user_id', ASCENDING), ('idempotency_key', ASCENDING)], unique=True, partialFilterExpression={'idempotency_key': {'$type': 'string'}}, name='runs_idempotency_unique')
    database.prompt_runs.create_index([('content_expires_at', ASCENDING)], name='runs_content_expiry')
    database.violations.create_index([('company_id', ASCENDING), ('run_id', ASCENDING), ('policy_id', ASCENDING), ('stage', ASCENDING)], unique=True, name='violations_unique_match')
    database.violations.create_index([('company_id', ASCENDING), ('resolution_status', ASCENDING), ('created_at', DESCENDING)], name='violations_review_queue')
    database.violations.create_index([('company_id', ASCENDING), ('user_id', ASCENDING), ('created_at', DESCENDING)], name='violations_owner_recent')
    database.notifications.create_index([('company_id', ASCENDING), ('recipient_user_id', ASCENDING), ('event_key', ASCENDING)], unique=True, name='notifications_recipient_event')
    database.notifications.create_index([('company_id', ASCENDING), ('recipient_user_id', ASCENDING), ('read_at', ASCENDING), ('created_at', DESCENDING)], name='notifications_recipient_recent')
    database.red_team_tests.create_index([('company_id', ASCENDING), ('created_at', DESCENDING), ('_id', DESCENDING)], name='red_team_tests_recent')
    database.red_team_tests.create_index([('company_id', ASCENDING), ('status', ASCENDING), ('created_at', DESCENDING)], name='red_team_tests_status')
    database.red_team_tests.create_index([('company_id', ASCENDING), ('integration_id', ASCENDING), ('status', ASCENDING)], name='red_team_tests_integration')
    database.red_team_jobs.create_index([('company_id', ASCENDING), ('test_id', ASCENDING), ('attack_index', ASCENDING)], unique=True, name='red_team_jobs_position')
    database.red_team_jobs.create_index([('company_id', ASCENDING), ('test_id', ASCENDING), ('state', ASCENDING)], name='red_team_jobs_state')
    database.red_team_jobs.create_index([('company_id', ASCENDING), ('test_id', ASCENDING), ('verdict', ASCENDING)], name='red_team_jobs_verdict')
    database.red_team_jobs.create_index([('dispatch_state', ASCENDING), ('next_attempt_at', ASCENDING), ('dispatch_lease_expires_at', ASCENDING)], name='red_team_jobs_dispatch')
    database.red_team_jobs.create_index([('state', ASCENDING), ('execution_lease_expires_at', ASCENDING)], name='red_team_jobs_recovery')
    database.red_team_jobs.create_index([('content_expires_at', ASCENDING)], name='red_team_jobs_content_expiry')
    database.integration_execution_locks.create_index([('company_id', ASCENDING), ('integration_id', ASCENDING)], unique=True, name='integration_execution_unique')
    database.integration_execution_locks.create_index([('lease_expires_at', ASCENDING)], name='integration_execution_lease')
    database.worker_heartbeats.create_index([('kind', ASCENDING), ('updated_at', DESCENDING)], name='worker_heartbeats_recent')
    database.worker_heartbeats.create_index([('expires_at', ASCENDING)], expireAfterSeconds=0, name='worker_heartbeats_expiry')
